# Generated by Django 3.0.7 on 2020-06-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(max_length=50)),
                ('behaviour_type', models.CharField(choices=[('SAFE', 'Safe'), ('EUCLID', 'Euclid'), ('KETER', 'Keter')], max_length=6)),
                ('image', models.ImageField(default='./uploads/default.png', upload_to='uploads/')),
                ('description', models.TextField()),
                ('monster_location', models.ManyToManyField(to='cage.Location')),
            ],
        ),
    ]
