# Generated by Django 3.0.7 on 2020-06-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/'),
        ),
    ]
