# Generated by Django 3.0.7 on 2020-06-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0002_auto_20200624_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=models.ImageField(default='/default0.png', upload_to=''),
        ),
    ]
