# Generated by Django 3.0.7 on 2020-06-25 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0003_auto_20200624_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
